# Defines which nodes are used in the system and how to connect to them.
# This element should only be referenced during the constructor's initial
# setup.
# All names must be unique.
# No other nodes are known.
# These names will be used for src and dest addresses for the Message
# The local nodes name is included in this list

configuration :
   - name : p1
     ip : 127.0.0.1
     port : 12340 # This is the incoming port on which MP will listen
                  # May be changed for further communication as usual

   - name : p2
     ip : 127.0.0.1
     port : 12341

   - name : p3
     ip : 128.237.217.4
     port : 12342

   - name : p4
     ip : 128.237.217.4
     port : 12343

sendRules :
   - action : drop # Ack message number 4 from bob to alice will not be sent
     kind : sendDrop

   - action : delay # Every Lookup message in the system will be delayed
     kind : sendDelay

   - action : duplicate # Every Lookup message in the system will be delayed
     kind : sendDuplicate

receiveRules :
   - action : drop # Ack message number 4 from bob to alice will not be sent
     kind : rcvDrop

   - action : delay # Every Lookup message in the system will be delayed
     kind : rcvDelay

   - action : duplicate # Every Lookup message in the system will be delayed
     kind : rcvDuplicate

   - action : drop # Every Lookup message in the system will be delayed
     kind : sendDuplicate
     duplicate : true
