# Defines which nodes are used in the system and how to connect to them.
# This element should only be referenced during the constructor's initial
# setup.
# All names must be unique.
# No other nodes are known.
# These names will be used for src and dest addresses for the Message
# The local nodes name is included in this list

configuration :
   - name : p1
     ip : 127.0.0.1
     port : 12340 # This is the incoming port on which MP will listen
                  # May be changed for further communication as usual

   - name : p2
     ip : 127.0.0.1
     port : 12341

   - name : charlie
     ip : 128.2.130.19
     port : 12998

   - name : daphnie
     ip : 192.168.1.87
     port : 1987

sendRules :
   - action : drop # Ack message number 4 from bob to alice will not be sent
     src : p1
     dest : p2
     kind : Ack
     seqNum : 4

   - action : delay # Every Lookup message in the system will be delayed
     kind : Lookup

   - action : duplicate
     seqNum : 2

   - action : drop # 3rd message from Charlie that anyone
     src : p1 # receives will be duplicated
     duplicate: true

receiveRules :
   - action : duplicate # 3rd message from Charlie that anyone
     src : p1 # receives will be duplicated

   - action : drop # Ack message number 4 from bob to alice will not be sent
     src : p1
     dest : p2
     kind : aaa

   - action : drop # Ack message number 4 from bob to alice will not be sent
     src : p1
     dest : p2
     duplicate: true

   - action : delay # Ack message number 4 from bob to alice will not be sent
     src : p1
     dest : p2
     kind : delay