# Defines which nodes are used in the system and how to connect to them.
# This element should only be referenced during the constructor's initial
# setup.
# All names must be unique.
# No other nodes are known.
# These names will be used for src and dest addresses for the Message
# The local nodes name is included in this list

configuration :
 - name : alice
   ip : 192.168.1.52
   port : 12344 # This is the incoming port on which MP will listen
# May be changed for further communication as usual
 - name : bob
   ip : 192.168.1.112
   port : 14255
 - name : charlie
   ip : 128.2.130.19
   port : 12998
 - name : daphnie
   ip : 192.168.1.87
   port : 1987